"""完善数据质量分析工作报告"""
import pandas as pd
from pathlib import Path
from datetime import datetime

PROJECT_ROOT = Path(__file__).parent
output_dir = PROJECT_ROOT / "outputs" / "middata"
output_dir.mkdir(parents=True, exist_ok=True)

# 读取Excel文件获取工作流程
excel_path = PROJECT_ROOT / "data" / "raw" / "source_data" / "数据处理工作流程.xlsx"
excel_data = pd.read_excel(excel_path, sheet_name=None)

# 读取异常值统计
anomaly_stats_path = PROJECT_ROOT / "outputs" / "middata" / "anomaly_statistics.csv"
anomaly_stats = pd.read_csv(anomaly_stats_path, encoding='utf-8-sig')

# 读取数据维度表
data_dimensions = excel_data.get('数据维度表', pd.DataFrame())
workflow = excel_data.get('数据处理工作流程', pd.DataFrame())

# 原始数据统计
raw_data_info = {
    "LC": {"总记录数": 328553, "字段数": 22, "表名": "借款主表"},
    "LP": {"总记录数": 3203276, "字段数": 10, "表名": "还款记录表"},
    "LCIS": {"总记录数": 292539, "字段数": 37, "表名": "标状态表"}
}

# 标签统计
label_stats = {
    "总记录数": 328553,
    "有效标签": 153950,
    "无效标签": 174603,
    "已还清（正常）": 67272,
    "逾期中（违约）": 86678,
    "有效标签占比": 46.85,
    "无效标签占比": 53.15
}

# 生成报告
report_lines = []
report_lines.append("=" * 80)
report_lines.append("PPDAI数据质量分析与清洗工作报告")
report_lines.append("=" * 80)
report_lines.append(f"报告生成时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
report_lines.append("")
report_lines.append("=" * 80)
report_lines.append("一、整体工作流程")
report_lines.append("=" * 80)
report_lines.append("")
report_lines.append("本次数据清洗工作严格按照《数据处理工作流程.xlsx》中的规范执行，主要包括以下步骤：")
report_lines.append("")

# 从Excel中读取工作流程详情
if not workflow.empty:
    for idx, row in workflow.iterrows():
        step_num = int(row.get('步骤', idx + 1))
        step_name = str(row.get('流程名称', '')).strip()
        step_detail = str(row.get('详细说明', '')).strip()
        
        if step_name and step_name != 'nan':
            report_lines.append(f"{step_num}. {step_name}")
            if step_detail and step_detail != 'nan':
                # 处理换行符和特殊字符
                details = step_detail.replace('\\n', '\n     ')
                # 分割多行说明
                for line in details.split('\n'):
                    line = line.strip()
                    if line:
                        report_lines.append(f"   {line}")
            report_lines.append("")

report_lines.append("1.1 数据加载阶段")
report_lines.append("   - 从data/raw/source_data目录读取三张原始数据表（LC.csv、LP.csv、LCIS.csv）")
report_lines.append("   - 统一编码格式为UTF-8，确保中文数据正确读取")
report_lines.append("   - 对日期字段进行类型转换，统一使用datetime64[ns]类型")
report_lines.append("   - 原始数据统计：")
report_lines.append(f"     * LC表（借款主表）: {raw_data_info['LC']['总记录数']:,} 条记录, {raw_data_info['LC']['字段数']} 个字段")
report_lines.append(f"     * LP表（还款记录表）: {raw_data_info['LP']['总记录数']:,} 条记录, {raw_data_info['LP']['字段数']} 个字段")
report_lines.append(f"     * LCIS表（标状态表）: {raw_data_info['LCIS']['总记录数']:,} 条记录, {raw_data_info['LCIS']['字段数']} 个字段")
report_lines.append("")
report_lines.append("1.2 数据质量分析阶段")
report_lines.append("   - 扫描所有数据表的缺失值和异常值")
report_lines.append("   - 统计异常值数量和占比")
report_lines.append("   - 识别数据质量问题类型")
report_lines.append("   - 生成异常值统计表（anomaly_statistics.csv）")
report_lines.append("")
report_lines.append("1.3 数据清洗阶段")
report_lines.append("   - 根据《数据处理方法.xlsx》中的规范，对68个数据维度进行严格清洗")
report_lines.append("   - LC表清洗：")
report_lines.append("     * 认证字段转换（手机认证、户口认证、视频认证、学历认证、征信认证、淘宝认证）：")
report_lines.append("       成功认证=1，未成功认证=0")
report_lines.append("     * 类别字段保持不变（初始评级、借款类型、是否首标、性别）：后续进行one-hot编码")
report_lines.append("     * 数值字段保持不变（根据规范，LC表所有数值字段都不变）")
report_lines.append("     * 添加新特征：正常还款比 = 历史正常还款期数 / (历史正常还款期数 + 历史逾期还款期数)")
report_lines.append("   - LP表清洗：")
report_lines.append("     * 还款状态重新赋值：0=正常还款中；1,3=已还清；2,4=逾期中")
report_lines.append("     * 其他字段保持不变")
report_lines.append("   - LCIS表清洗：")
report_lines.append("     * 认证字段处理：视频认证、学历认证、征信认证、淘宝认证转换为0/1")
report_lines.append("     * 历史正常还款期数、历史逾期还款期数：以99%分位数值为极大值，超过的取极大值")
report_lines.append("     * 标当前状态：只保留'正常还款中'，'逾期中'，'已还清'，其他删除（设为缺失）")
report_lines.append("     * 上次还款日期：删除非日期项（设为缺失）")
report_lines.append("")
report_lines.append("1.4 标签生成阶段")
report_lines.append("   - 优先使用LCIS表的'标当前状态'作为因变量")
report_lines.append("   - 使用LP表的'还款状态'作为补充")
report_lines.append("   - 只保留'已还清'（标签=0）和'逾期中'（标签=1）作为有效的因变量")
report_lines.append("   - 排除'正常还款中'的记录（还未产生结果）")
report_lines.append(f"   - 标签统计：总记录数={label_stats['总记录数']:,}，有效标签={label_stats['有效标签']:,}（{label_stats['有效标签占比']}%），无效标签={label_stats['无效标签']:,}（{label_stats['无效标签占比']}%）")
report_lines.append("")
report_lines.append("1.5 特征工程阶段")
report_lines.append("   - 时间特征提取：从借款成功日期中提取年份、月份、季度、星期等特征")
report_lines.append("   - 衍生特征构造：历史逾期率、借款杠杆比、待还本金占比等")
report_lines.append("   - LP特征聚合：将还款记录表按ListingId聚合，生成借款级别的特征")
report_lines.append("   - 类别特征编码：对类别特征进行one-hot编码")
report_lines.append("   - 自动处理：将object类型的binary特征自动移到categorical特征中进行one-hot编码")
report_lines.append("")
report_lines.append("1.6 数据切分阶段")
report_lines.append("   - 尝试使用时序切分策略（基于借款成功日期）")
report_lines.append("   - 如果时序切分导致某个集合为空，则回退到随机分层切分策略")
report_lines.append("   - 最终数据集划分：")
report_lines.append("     * 训练集: 107,765 条记录")
report_lines.append("     * 验证集: 23,092 条记录")
report_lines.append("     * 测试集: 23,093 条记录")
report_lines.append("")
report_lines.append("1.7 特征标准化阶段")
report_lines.append("   - 对数值特征进行标准化（StandardScaler）")
report_lines.append("   - 保存标准化器（numeric_scaler.pkl）以便后续推理使用")
report_lines.append("")
report_lines.append("=" * 80)
report_lines.append("二、原始数据质量分析")
report_lines.append("=" * 80)
report_lines.append("")
report_lines.append("2.1 数据完整性分析")
report_lines.append("")
report_lines.append("根据异常值统计表，主要数据质量问题如下：")
report_lines.append("")

# 按表名分组统计
for table_name in ['LC', 'LP', 'LCIS']:
    table_stats = anomaly_stats[anomaly_stats['表名'] == table_name]
    if not table_stats.empty:
        report_lines.append(f"{table_name}表数据质量问题：")
        for idx, row in table_stats.iterrows():
            data_item = row['数据项']
            anomaly_count = int(row['异常值数量'])
            total_count = int(row['总记录数'])
            anomaly_rate = float(row['异常值占比'])
            report_lines.append(f"   - {data_item}:")
            report_lines.append(f"     异常值数量: {anomaly_count:,} 条")
            report_lines.append(f"     总记录数: {total_count:,} 条")
            report_lines.append(f"     异常值占比: {anomaly_rate:.2f}%")
        report_lines.append("")

report_lines.append("2.2 主要数据质量问题汇总")
report_lines.append("")
report_lines.append("(1) 缺失值问题（按严重程度排序）：")
report_lines.append("   - LP表：还款日期缺失值占比高达48.72%（1,560,671条），这是最大的数据质量问题")
report_lines.append("     * 原因分析：这些记录主要是还未到期的借款或还未还款的记录")
report_lines.append("     * 影响：无法准确计算还款延迟天数，影响模型特征工程")
report_lines.append("   - LCIS表：下次计划还款相关字段缺失值占比37.96%（111,045条）")
report_lines.append("     * 原因分析：借款已还清、已逾期或已结清，不再需要计划还款")
report_lines.append("     * 影响：无法准确分析还款计划，但不影响已还清/逾期的标签判断")
report_lines.append("   - LCIS表：上次还款相关字段缺失值占比7.61%（22,249条）")
report_lines.append("     * 原因分析：首次借款、还未还款或借款刚成立")
report_lines.append("     * 影响：无法准确分析历史还款记录，但对新用户影响较小")
report_lines.append("   - LCIS表：历史成功借款相关字段缺失值占比0.41%（1,203条）")
report_lines.append("     * 原因分析：新用户，还没有历史借款记录")
report_lines.append("     * 影响：无法准确分析历史信用，但对新用户影响较小")
report_lines.append("")
report_lines.append("(2) 异常值问题：")
report_lines.append("   - LC表：年龄超出范围（18-70岁）的记录有2条，占比0.00%")
report_lines.append("     * 原因分析：数据录入错误或数据迁移过程中的问题")
report_lines.append("     * 影响：影响较小，但需要清洗处理")
report_lines.append("")
report_lines.append("(3) 标签可用性问题：")
report_lines.append(f"   - 总记录数: {label_stats['总记录数']:,} 条")
report_lines.append(f"   - 有效标签: {label_stats['有效标签']:,} 条（{label_stats['有效标签占比']}%）")
report_lines.append(f"     * 已还清（正常）: {label_stats['已还清（正常）']:,} 条")
report_lines.append(f"     * 逾期中（违约）: {label_stats['逾期中（违约）']:,} 条")
report_lines.append(f"   - 无效标签: {label_stats['无效标签']:,} 条（{label_stats['无效标签占比']}%）")
report_lines.append("     * 无效标签主要来自'正常还款中'的记录，这些记录还未产生最终结果")
report_lines.append("     * 这些记录无法用于模型训练，因为无法确定最终的还款结果")
report_lines.append("")
report_lines.append("2.3 数据质量评估")
report_lines.append("")
report_lines.append("(1) 数据完整性评估：")
report_lines.append("   - 整体完整性：较好，大部分字段完整性在90%以上")
report_lines.append("   - 主要问题：还款日期缺失率较高（48.72%），但这主要是业务逻辑导致")
report_lines.append("   - 建议：对业务逻辑导致的缺失值，需要在特征工程中合理处理")
report_lines.append("")
report_lines.append("(2) 数据准确性评估：")
report_lines.append("   - 整体准确性：较好，异常值占比很小（年龄异常值仅0.00%）")
report_lines.append("   - 主要问题：年龄字段存在少量异常值")
report_lines.append("   - 建议：加强数据验证，在数据采集时进行实时验证")
report_lines.append("")
report_lines.append("(3) 数据一致性评估：")
report_lines.append("   - 整体一致性：较好，数据格式基本统一")
report_lines.append("   - 主要问题：认证字段格式不统一（字符串 vs 数值）")
report_lines.append("   - 建议：统一数据格式，在数据采集时进行格式验证")
report_lines.append("")
report_lines.append("(4) 标签可用性评估：")
report_lines.append(f"   - 标签可用率：{label_stats['有效标签占比']}%")
report_lines.append("   - 主要问题：53.15%的记录处于'正常还款中'状态，无法用于模型训练")
report_lines.append("   - 建议：对于'正常还款中'的记录，需要等待还款完成后再使用")
report_lines.append("")
report_lines.append("=" * 80)
report_lines.append("三、不可用数据的类型")
report_lines.append("=" * 80)
report_lines.append("")
report_lines.append("根据本次数据清洗的实际情况，不可用数据主要包括以下类型：")
report_lines.append("")
report_lines.append("3.1 缺失值类型")
report_lines.append("   (1) 完全缺失：字段值为空（NULL/NaN）")
report_lines.append("      - 还款日期缺失：LP表中48.72%的记录缺失还款日期")
report_lines.append("        * 类型：业务逻辑导致的缺失（还未到期或还未还款）")
report_lines.append("        * 处理方式：保留缺失值，在特征工程中合理处理")
report_lines.append("      - 下次计划还款日期/利息/本金缺失：LCIS表中37.96%的记录缺失")
report_lines.append("        * 类型：业务逻辑导致的缺失（借款已还清、已逾期或已结清）")
report_lines.append("        * 处理方式：保留缺失值，不影响标签判断")
report_lines.append("      - 上次还款日期/利息/本金缺失：LCIS表中7.61%的记录缺失")
report_lines.append("        * 类型：业务逻辑导致的缺失（首次借款、还未还款或借款刚成立）")
report_lines.append("        * 处理方式：保留缺失值，对新用户影响较小")
report_lines.append("      - 历史成功借款次数/金额缺失：LCIS表中0.41%的记录缺失")
report_lines.append("        * 类型：业务逻辑导致的缺失（新用户，还没有历史借款记录）")
report_lines.append("        * 处理方式：保留缺失值，对新用户影响较小")
report_lines.append("   (2) 部分缺失：字段值部分缺失")
report_lines.append("      - recorddate缺失：LCIS表中0.41%的记录缺失记录日期")
report_lines.append("        * 类型：数据采集导致的缺失")
report_lines.append("        * 处理方式：保留缺失值，在特征工程中合理处理")
report_lines.append("")
report_lines.append("3.2 异常值类型")
report_lines.append("   (1) 数值范围异常：")
report_lines.append("      - 年龄超出合理范围：LC表中有2条记录的年龄不在18-70岁范围内")
report_lines.append("        * 类型：数据录入错误或数据迁移过程中的问题")
report_lines.append("        * 处理方式：在数据清洗时设为缺失值，后续填充或删除")
report_lines.append("   (2) 日期格式异常：")
report_lines.append("      - 日期字段无法解析为有效日期格式")
report_lines.append("        * 类型：数据格式错误")
report_lines.append("        * 处理方式：在数据清洗时设为缺失值")
report_lines.append("   (3) 状态值异常：")
report_lines.append("      - 标当前状态包含非标准值（非'正常还款中'、'逾期中'、'已还清'）")
report_lines.append("        * 类型：数据格式错误或业务逻辑变更")
report_lines.append("        * 处理方式：在数据清洗时设为缺失值")
report_lines.append("")
report_lines.append("3.3 标签不可用类型")
report_lines.append("   (1) 未完成状态：")
report_lines.append(f"      - '正常还款中'的记录：{label_stats['无效标签']:,} 条（{label_stats['无效标签占比']}%）")
report_lines.append("        * 类型：业务流程中的中间状态")
report_lines.append("        * 处理方式：排除这些记录，不用于模型训练")
report_lines.append("   (2) 状态缺失：")
report_lines.append("      - LCIS表和LP表中都缺失状态信息的记录")
report_lines.append("        * 类型：数据采集不完整")
report_lines.append("        * 处理方式：排除这些记录，不用于模型训练")
report_lines.append("")
report_lines.append("3.4 数据类型不一致")
report_lines.append("   (1) 认证字段格式不统一：")
report_lines.append("      - 认证字段可能包含字符串（'成功'、'是'等）或数值（1、0等）")
report_lines.append("        * 类型：数据采集格式不统一")
report_lines.append("        * 处理方式：在数据清洗时统一转换为0/1格式")
report_lines.append("   (2) 类别字段格式不统一：")
report_lines.append("      - '是否首标'字段包含字符串（'是'、'否'），需要转换为数值或进行one-hot编码")
report_lines.append("        * 类型：数据采集格式不统一")
report_lines.append("        * 处理方式：在特征工程时自动进行one-hot编码")
report_lines.append("")
report_lines.append("=" * 80)
report_lines.append("四、产生不可用数据的原因分析")
report_lines.append("=" * 80)
report_lines.append("")
report_lines.append("4.1 业务逻辑原因")
report_lines.append("   (1) 业务流程导致的数据缺失：")
report_lines.append("      - 还款日期缺失（48.72%）：主要是因为这些借款还未到期或还未还款")
report_lines.append("        * 这是正常的业务逻辑，因为只有在还款完成后才会记录还款日期")
report_lines.append("        * 影响：无法准确计算还款延迟天数，但可以通过其他方式处理")
report_lines.append("      - 下次计划还款日期缺失（37.96%）：可能是因为借款已还清、已逾期或已结清")
report_lines.append("        * 这是正常的业务逻辑，因为已还清/逾期的借款不再需要计划还款")
report_lines.append("        * 影响：无法准确分析还款计划，但不影响标签判断")
report_lines.append("      - 上次还款日期缺失（7.61%）：可能是因为首次借款、还未还款或借款刚成立")
report_lines.append("        * 这是正常的业务逻辑，因为首次借款或刚成立的借款还没有还款记录")
report_lines.append("        * 影响：无法准确分析历史还款记录，但对新用户影响较小")
report_lines.append("   (2) 用户状态导致的数据缺失：")
report_lines.append("      - 历史成功借款次数/金额缺失（0.41%）：可能是因为新用户，还没有历史借款记录")
report_lines.append("        * 这是正常的业务逻辑，因为新用户还没有历史数据")
report_lines.append("        * 影响：无法准确分析历史信用，但对新用户影响较小")
report_lines.append("   (3) 业务流程中的中间状态：")
report_lines.append(f"      - '正常还款中'的记录（{label_stats['无效标签占比']}%）：这些记录处于还款过程中，还未产生最终结果")
report_lines.append("        * 这是正常的业务逻辑，因为借款还未完成，无法确定最终结果")
report_lines.append("        * 影响：无法用于模型训练，因为无法确定最终的还款结果")
report_lines.append("")
report_lines.append("4.2 数据采集原因")
report_lines.append("   (1) 数据采集不完整：")
report_lines.append("      - 部分字段在数据采集时未强制要求填写，导致缺失")
report_lines.append("        * 原因：数据采集规范不严格，未设置必填项")
report_lines.append("        * 影响：导致数据完整性不足，影响模型特征工程")
report_lines.append("      - 部分字段在业务流程的不同阶段采集，导致某些阶段的记录缺失")
report_lines.append("        * 原因：数据采集时机不当，未在合适的时机采集数据")
report_lines.append("        * 影响：导致数据不一致，影响模型特征工程")
report_lines.append("   (2) 数据采集时机不当：")
report_lines.append("      - 还款日期在还款完成后才记录，导致未还款的记录缺失")
report_lines.append("        * 原因：数据采集时机不当，未在借款成立时记录计划还款日期")
report_lines.append("        * 影响：导致数据缺失，影响模型特征工程")
report_lines.append("      - 下次计划还款日期在借款成立时记录，但在还款完成后可能不再更新")
report_lines.append("        * 原因：数据更新不及时，未在还款完成后更新状态")
report_lines.append("        * 影响：导致数据不一致，影响模型特征工程")
report_lines.append("   (3) 数据采集格式不统一：")
report_lines.append("      - 认证字段可能来自不同的数据源，格式不统一（字符串 vs 数值）")
report_lines.append("        * 原因：数据采集系统不统一，未统一数据格式")
report_lines.append("        * 影响：导致数据格式不一致，需要在数据清洗时统一处理")
report_lines.append("      - 类别字段可能来自用户输入，格式不统一（'是'/'否' vs 1/0）")
report_lines.append("        * 原因：数据采集界面不统一，未统一数据格式")
report_lines.append("        * 影响：导致数据格式不一致，需要在特征工程时统一处理")
report_lines.append("")
report_lines.append("4.3 数据存储原因")
report_lines.append("   (1) 数据库设计问题：")
report_lines.append("      - 部分字段允许NULL值，导致缺失值")
report_lines.append("        * 原因：数据库设计时未考虑数据完整性，允许NULL值")
report_lines.append("        * 影响：导致数据缺失，影响模型特征工程")
report_lines.append("      - 部分字段未设置默认值，导致空值")
report_lines.append("        * 原因：数据库设计时未设置默认值")
report_lines.append("        * 影响：导致数据缺失，影响模型特征工程")
report_lines.append("   (2) 数据迁移问题：")
report_lines.append("      - 数据迁移过程中可能丢失部分数据")
report_lines.append("        * 原因：数据迁移工具不完善，未完整迁移数据")
report_lines.append("        * 影响：导致数据缺失，影响模型特征工程")
report_lines.append("      - 数据格式转换过程中可能出现错误")
report_lines.append("        * 原因：数据格式转换工具不完善，未正确处理数据格式")
report_lines.append("        * 影响：导致数据格式错误，需要在数据清洗时处理")
report_lines.append("   (3) 数据更新问题：")
report_lines.append("      - 部分字段在业务流程中未及时更新")
report_lines.append("        * 原因：数据更新机制不完善，未及时更新数据")
report_lines.append("        * 影响：导致数据不一致，影响模型特征工程")
report_lines.append("      - 部分字段在状态变更时未同步更新")
report_lines.append("        * 原因：数据同步机制不完善，未同步更新数据")
report_lines.append("        * 影响：导致数据不一致，影响模型特征工程")
report_lines.append("")
report_lines.append("4.4 数据验证原因")
report_lines.append("   (1) 数据验证不严格：")
report_lines.append("      - 年龄字段未设置范围检查，导致超出合理范围的值")
report_lines.append("        * 原因：数据验证规则不完善，未设置范围检查")
report_lines.append("        * 影响：导致数据异常，需要在数据清洗时处理")
report_lines.append("      - 日期字段未设置格式验证，导致格式错误的值")
report_lines.append("        * 原因：数据验证规则不完善，未设置格式验证")
report_lines.append("        * 影响：导致数据格式错误，需要在数据清洗时处理")
report_lines.append("      - 状态字段未设置枚举值检查，导致非标准值")
report_lines.append("        * 原因：数据验证规则不完善，未设置枚举值检查")
report_lines.append("        * 影响：导致数据格式错误，需要在数据清洗时处理")
report_lines.append("   (2) 数据清洗不及时：")
report_lines.append("      - 历史数据中积累的异常值未及时清理")
report_lines.append("        * 原因：数据清洗机制不完善，未及时清洗数据")
report_lines.append("        * 影响：导致数据质量下降，影响模型特征工程")
report_lines.append("      - 数据质量监控不足，未能及时发现数据问题")
report_lines.append("        * 原因：数据质量监控机制不完善，未及时监控数据质量")
report_lines.append("        * 影响：导致数据问题积累，影响模型特征工程")
report_lines.append("")
report_lines.append("=" * 80)
report_lines.append("五、如何避免产生不可用数据")
report_lines.append("=" * 80)
report_lines.append("")
report_lines.append("5.1 数据采集阶段优化")
report_lines.append("   (1) 建立数据采集规范：")
report_lines.append("      - 制定统一的数据采集标准，明确每个字段的数据类型、格式和取值范围")
report_lines.append("      - 对关键字段设置必填项，减少缺失值")
report_lines.append("      - 对枚举类型字段提供下拉选项，避免非标准值")
report_lines.append("      - 建立数据采集规范文档，确保数据采集人员遵循规范")
report_lines.append("   (2) 实施数据验证：")
report_lines.append("      - 在数据采集时进行实时验证，及时发现和纠正数据问题")
report_lines.append("      - 对年龄、金额等数值字段设置范围检查")
report_lines.append("      - 对日期字段进行格式验证")
report_lines.append("      - 对状态字段进行枚举值检查")
report_lines.append("      - 建立数据验证规则库，统一数据验证标准")
report_lines.append("   (3) 统一数据格式：")
report_lines.append("      - 认证字段统一使用0/1表示，避免字符串和数值混用")
report_lines.append("      - 类别字段统一使用标准值，避免格式不统一")
report_lines.append("      - 日期字段统一使用标准格式（YYYY-MM-DD）")
report_lines.append("      - 建立数据格式标准，确保数据格式统一")
report_lines.append("")
report_lines.append("5.2 数据存储阶段优化")
report_lines.append("   (1) 数据库设计优化：")
report_lines.append("      - 对关键字段设置NOT NULL约束，减少缺失值")
report_lines.append("      - 对枚举类型字段使用ENUM类型，避免非标准值")
report_lines.append("      - 对数值字段设置范围检查（CHECK约束）")
report_lines.append("      - 对日期字段设置格式验证")
report_lines.append("      - 建立数据库设计规范，确保数据库设计合理")
report_lines.append("   (2) 数据完整性约束：")
report_lines.append("      - 建立外键约束，确保数据关联完整性")
report_lines.append("      - 建立唯一性约束，避免重复数据")
report_lines.append("      - 建立检查约束，确保数据值的合理性")
report_lines.append("      - 建立数据完整性约束规范，确保数据完整性")
report_lines.append("   (3) 数据默认值设置：")
report_lines.append("      - 对可选字段设置合理的默认值")
report_lines.append("      - 对状态字段设置初始状态")
report_lines.append("      - 对时间字段设置自动更新时间戳")
report_lines.append("      - 建立数据默认值规范，确保数据默认值合理")
report_lines.append("")
report_lines.append("5.3 数据更新阶段优化")
report_lines.append("   (1) 实时数据更新：")
report_lines.append("      - 在业务流程关键节点及时更新数据")
report_lines.append("      - 建立数据同步机制，确保数据一致性")
report_lines.append("      - 对状态变更建立触发器，自动更新相关字段")
report_lines.append("      - 建立数据更新机制，确保数据及时更新")
report_lines.append("   (2) 数据版本管理：")
report_lines.append("      - 建立数据版本管理机制，记录数据变更历史")
report_lines.append("      - 对重要字段变更进行审计，便于追溯")
report_lines.append("      - 建立数据版本管理规范，确保数据版本管理合理")
report_lines.append("   (3) 数据清理机制：")
report_lines.append("      - 定期清理历史数据中的异常值")
report_lines.append("      - 建立数据质量监控机制，及时发现数据问题")
report_lines.append("      - 对长期未更新的数据进行标记和处理")
report_lines.append("      - 建立数据清理机制，确保数据质量")
report_lines.append("")
report_lines.append("5.4 数据质量监控")
report_lines.append("   (1) 建立数据质量指标体系：")
report_lines.append("      - 完整性指标：缺失值率、空值率")
report_lines.append("      - 准确性指标：异常值率、格式错误率")
report_lines.append("      - 一致性指标：数据冲突率、重复率")
report_lines.append("      - 及时性指标：数据更新延迟率")
report_lines.append("      - 建立数据质量指标体系，确保数据质量可量化")
report_lines.append("   (2) 实施数据质量监控：")
report_lines.append("      - 建立数据质量监控系统，实时监控数据质量")
report_lines.append("      - 设置数据质量告警阈值，及时发现数据问题")
report_lines.append("      - 定期生成数据质量报告，分析数据质量趋势")
report_lines.append("      - 建立数据质量监控机制，确保数据质量可控")
report_lines.append("   (3) 数据质量改进：")
report_lines.append("      - 根据数据质量监控结果，及时改进数据采集和存储流程")
report_lines.append("      - 建立数据质量改进机制，持续提升数据质量")
report_lines.append("      - 建立数据质量改进规范，确保数据质量持续改进")
report_lines.append("")
report_lines.append("=" * 80)
report_lines.append("六、更加高效和有效的数据采集方式")
report_lines.append("=" * 80)
report_lines.append("")
report_lines.append("6.1 自动化数据采集")
report_lines.append("   (1) 系统自动采集：")
report_lines.append("      - 在业务流程关键节点自动采集数据，减少人工录入")
report_lines.append("        * 在借款成立时自动记录借款信息")
report_lines.append("        * 在还款完成时自动记录还款信息")
report_lines.append("        * 在状态变更时自动更新状态信息")
report_lines.append("      - 建立数据采集API，统一数据采集接口")
report_lines.append("        * 建立统一的数据采集API，确保数据采集接口一致")
report_lines.append("        * 建立数据采集API文档，方便数据采集人员使用")
report_lines.append("      - 使用数据采集工具，自动从各个数据源采集数据")
report_lines.append("        * 使用ETL工具（如Apache NiFi）进行数据采集")
report_lines.append("        * 使用数据集成工具（如Airflow）进行数据集成")
report_lines.append("   (2) 实时数据采集：")
report_lines.append("      - 建立实时数据采集机制，及时采集业务数据")
report_lines.append("        * 使用消息队列（如Kafka）进行实时数据流处理")
report_lines.append("        * 使用流处理框架（如Spark Streaming）进行实时数据处理")
report_lines.append("      - 建立数据采集监控，确保数据采集的及时性")
report_lines.append("        * 建立数据采集监控系统，实时监控数据采集状态")
report_lines.append("        * 设置数据采集告警阈值，及时发现数据采集问题")
report_lines.append("   (3) 批量数据采集：")
report_lines.append("      - 对历史数据进行批量采集和清洗")
report_lines.append("        * 使用批量数据处理工具（如Spark）进行批量数据处理")
report_lines.append("        * 建立批量数据处理任务，定期同步数据")
report_lines.append("      - 建立批量数据采集任务，定期同步数据")
report_lines.append("        * 使用ETL工具（如Airflow）进行批量数据处理")
report_lines.append("        * 建立批量数据处理任务调度，确保数据处理及时")
report_lines.append("")
report_lines.append("6.2 数据验证和清洗")
report_lines.append("   (1) 数据验证规则：")
report_lines.append("      - 建立数据验证规则库，统一数据验证标准")
report_lines.append("        * 建立数据验证规则库，存储所有数据验证规则")
report_lines.append("        * 建立数据验证规则文档，方便数据验证人员使用")
report_lines.append("      - 在数据采集时进行实时验证，及时发现数据问题")
report_lines.append("        * 在数据采集时进行实时验证，及时发现和纠正数据问题")
report_lines.append("        * 建立数据验证告警机制，及时通知数据问题")
report_lines.append("      - 对验证失败的数据进行标记和告警")
report_lines.append("        * 对验证失败的数据进行标记，便于后续处理")
report_lines.append("        * 建立数据验证告警机制，及时通知数据问题")
report_lines.append("   (2) 数据清洗规则：")
report_lines.append("      - 建立数据清洗规则库，统一数据清洗标准")
report_lines.append("        * 建立数据清洗规则库，存储所有数据清洗规则")
report_lines.append("        * 建立数据清洗规则文档，方便数据清洗人员使用")
report_lines.append("      - 对常见的数据问题建立自动清洗规则")
report_lines.append("        * 对常见的数据问题建立自动清洗规则，减少人工清洗")
report_lines.append("        * 建立数据清洗规则库，存储所有数据清洗规则")
report_lines.append("      - 对无法自动清洗的数据进行人工审核")
report_lines.append("        * 对无法自动清洗的数据进行人工审核，确保数据质量")
report_lines.append("        * 建立数据清洗审核机制，确保数据清洗质量")
report_lines.append("   (3) 数据质量反馈：")
report_lines.append("      - 建立数据质量反馈机制，将数据质量问题反馈给数据采集方")
report_lines.append("        * 建立数据质量反馈系统，及时反馈数据质量问题")
report_lines.append("        * 建立数据质量反馈机制，确保数据质量问题及时解决")
report_lines.append("      - 对数据质量问题进行跟踪和改进")
report_lines.append("        * 对数据质量问题进行跟踪，确保问题及时解决")
report_lines.append("        * 建立数据质量改进机制，持续提升数据质量")
report_lines.append("")
report_lines.append("6.3 数据标准化")
report_lines.append("   (1) 数据格式标准化：")
report_lines.append("      - 建立数据格式标准，统一数据格式")
report_lines.append("        * 建立数据格式标准文档，明确每个字段的数据格式")
report_lines.append("        * 建立数据格式验证规则，确保数据格式符合标准")
report_lines.append("      - 对数据格式进行自动转换，确保数据一致性")
report_lines.append("        * 建立数据格式转换工具，自动转换数据格式")
report_lines.append("        * 建立数据格式转换规则，确保数据格式转换正确")
report_lines.append("      - 建立数据格式验证，确保数据符合标准")
report_lines.append("        * 建立数据格式验证系统，实时验证数据格式")
report_lines.append("        * 建立数据格式验证告警机制，及时通知数据格式问题")
report_lines.append("   (2) 数据编码标准化：")
report_lines.append("      - 建立数据编码标准，统一数据编码")
report_lines.append("        * 建立数据编码标准文档，明确每个字段的数据编码")
report_lines.append("        * 建立数据编码验证规则，确保数据编码符合标准")
report_lines.append("      - 对枚举类型字段建立标准编码表")
report_lines.append("        * 建立标准编码表，存储所有枚举类型字段的标准编码")
report_lines.append("        * 建立标准编码表文档，方便数据编码人员使用")
report_lines.append("      - 对数据编码进行自动转换，确保数据一致性")
report_lines.append("        * 建立数据编码转换工具，自动转换数据编码")
report_lines.append("        * 建立数据编码转换规则，确保数据编码转换正确")
report_lines.append("   (3) 数据字典管理：")
report_lines.append("      - 建立数据字典，统一数据定义")
report_lines.append("        * 建立数据字典系统，存储所有数据定义")
report_lines.append("        * 建立数据字典文档，方便数据使用人员使用")
report_lines.append("      - 对数据字典进行版本管理，确保数据定义的一致性")
report_lines.append("        * 建立数据字典版本管理机制，记录数据定义变更历史")
report_lines.append("        * 建立数据字典版本管理规范，确保数据定义一致性")
report_lines.append("      - 建立数据字典查询系统，方便数据使用")
report_lines.append("        * 建立数据字典查询系统，方便数据使用人员查询")
report_lines.append("        * 建立数据字典查询文档，方便数据使用人员使用")
report_lines.append("")
report_lines.append("6.4 数据采集工具和技术")
report_lines.append("   (1) 数据采集工具：")
report_lines.append("      - 使用数据采集工具（如Flume、Logstash）进行数据采集")
report_lines.append("        * Flume：用于日志数据采集")
report_lines.append("        * Logstash：用于日志数据采集和处理")
report_lines.append("      - 使用数据集成工具（如Apache NiFi）进行数据集成")
report_lines.append("        * Apache NiFi：用于数据流处理和集成")
report_lines.append("      - 使用数据同步工具（如Canal）进行数据同步")
report_lines.append("        * Canal：用于数据库增量数据同步")
report_lines.append("   (2) 数据存储技术：")
report_lines.append("      - 使用分布式存储系统（如HDFS）存储大量数据")
report_lines.append("        * HDFS：用于大数据存储")
report_lines.append("      - 使用数据仓库（如Hive）进行数据分析")
report_lines.append("        * Hive：用于大数据分析")
report_lines.append("      - 使用数据湖（如Delta Lake）进行数据管理")
report_lines.append("        * Delta Lake：用于数据湖管理")
report_lines.append("   (3) 数据处理技术：")
report_lines.append("      - 使用流处理框架（如Spark Streaming）进行实时数据处理")
report_lines.append("        * Spark Streaming：用于实时数据处理")
report_lines.append("      - 使用批处理框架（如Spark）进行批量数据处理")
report_lines.append("        * Spark：用于批量数据处理")
report_lines.append("      - 使用机器学习框架（如MLflow）进行模型训练")
report_lines.append("        * MLflow：用于机器学习模型管理")
report_lines.append("")
report_lines.append("6.5 数据采集流程优化")
report_lines.append("   (1) 数据采集流程设计：")
report_lines.append("      - 设计合理的数据采集流程，减少数据采集环节")
report_lines.append("        * 在业务流程关键节点自动采集数据")
report_lines.append("        * 减少人工录入环节，提高数据采集效率")
report_lines.append("      - 建立数据采集流程监控，确保数据采集的及时性")
report_lines.append("        * 建立数据采集流程监控系统，实时监控数据采集状态")
report_lines.append("        * 设置数据采集流程告警阈值，及时发现数据采集问题")
report_lines.append("      - 对数据采集流程进行优化，提高数据采集效率")
report_lines.append("        * 对数据采集流程进行优化，减少数据采集时间")
report_lines.append("        * 建立数据采集流程优化机制，持续提升数据采集效率")
report_lines.append("   (2) 数据采集权限管理：")
report_lines.append("      - 建立数据采集权限管理机制，确保数据采集的安全性")
report_lines.append("        * 建立数据采集权限管理系统，管理数据采集权限")
report_lines.append("        * 建立数据采集权限管理规范，确保数据采集安全")
report_lines.append("      - 对数据采集人员进行培训，提高数据采集质量")
report_lines.append("        * 对数据采集人员进行培训，提高数据采集技能")
report_lines.append("        * 建立数据采集培训机制，持续提升数据采集质量")
report_lines.append("      - 建立数据采集审计机制，跟踪数据采集活动")
report_lines.append("        * 建立数据采集审计系统，跟踪数据采集活动")
report_lines.append("        * 建立数据采集审计规范，确保数据采集可追溯")
report_lines.append("   (3) 数据采集质量控制：")
report_lines.append("      - 建立数据采集质量控制机制，确保数据采集质量")
report_lines.append("        * 建立数据采集质量控制系统，监控数据采集质量")
report_lines.append("        * 建立数据采集质量控制规范，确保数据采集质量")
report_lines.append("      - 对数据采集结果进行抽样检查，及时发现数据问题")
report_lines.append("        * 对数据采集结果进行抽样检查，及时发现数据问题")
report_lines.append("        * 建立数据采集质量检查机制，确保数据采集质量")
report_lines.append("      - 建立数据采集质量评估机制，持续改进数据采集质量")
report_lines.append("        * 建立数据采集质量评估系统，评估数据采集质量")
report_lines.append("        * 建立数据采集质量评估机制，持续改进数据采集质量")
report_lines.append("")
report_lines.append("=" * 80)
report_lines.append("七、总结与建议")
report_lines.append("=" * 80)
report_lines.append("")
report_lines.append("7.1 数据质量总结")
report_lines.append("   - 本次数据清洗共处理了三张数据表，总计3,825,368条记录")
report_lines.append("   - 主要数据质量问题：")
report_lines.append("     * 缺失值问题：还款日期缺失48.72%，下次计划还款日期缺失37.96%")
report_lines.append("     * 异常值问题：年龄异常值仅0.00%，影响较小")
report_lines.append(f"     * 标签可用性问题：{label_stats['无效标签占比']}%的记录处于'正常还款中'状态，无法用于模型训练")
report_lines.append("   - 数据清洗后，最终得到153,950条有效标签记录，用于模型训练")
report_lines.append("   - 数据质量整体较好，主要问题来自业务逻辑导致的缺失值")
report_lines.append("")
report_lines.append("7.2 改进建议")
report_lines.append("   (1) 短期改进（1-3个月）：")
report_lines.append("      - 建立数据验证规则，在数据采集时进行实时验证")
report_lines.append("      - 对关键字段设置必填项，减少缺失值")
report_lines.append("      - 统一数据格式，避免格式不统一的问题")
report_lines.append("      - 建立数据质量监控系统，实时监控数据质量")
report_lines.append("   (2) 中期改进（3-6个月）：")
report_lines.append("      - 建立数据清洗规则库，统一数据清洗标准")
report_lines.append("      - 建立数据质量反馈机制，将数据质量问题反馈给数据采集方")
report_lines.append("      - 建立数据标准化体系，统一数据定义和格式")
report_lines.append("      - 建立自动化数据采集系统，减少人工录入")
report_lines.append("   (3) 长期改进（6-12个月）：")
report_lines.append("      - 建立数据质量改进机制，持续提升数据质量")
report_lines.append("      - 建立数据采集流程优化机制，持续提升数据采集效率")
report_lines.append("      - 建立数据质量评估机制，持续改进数据质量")
report_lines.append("      - 建立数据质量管理体系，确保数据质量持续改进")
report_lines.append("")
report_lines.append("7.3 数据采集优化建议")
report_lines.append("   - 在业务流程关键节点自动采集数据，减少人工录入")
report_lines.append("   - 建立实时数据采集机制，及时采集业务数据")
report_lines.append("   - 建立数据验证和清洗规则，确保数据质量")
report_lines.append("   - 建立数据质量监控系统，及时发现数据问题")
report_lines.append("   - 建立数据标准化体系，统一数据定义和格式")
report_lines.append("   - 建立数据采集流程优化机制，持续提升数据采集效率")
report_lines.append("")
report_lines.append("=" * 80)
report_lines.append("报告结束")
report_lines.append("=" * 80)
report_lines.append("")
report_lines.append("注：本报告基于本次数据清洗的实际情况生成，仅供参考。")
report_lines.append("")

# 写入文件
report_path = output_dir / "数据质量分析工作报告.txt"
with open(report_path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(report_lines))

print(f"报告已生成: {report_path}")
print(f"报告行数: {len(report_lines)}")
print(f"报告大小: {report_path.stat().st_size / 1024:.2f} KB")


